INSERT INTO Products (ID,PRODUCT_ID,PRODUCT_NAME,PRODUCT_PRICE,PRODUCT_ARTICLE,PRODUCT_QUANTITY,DATE_CREATE) VALUES (1,142,'Kartoshka',290, 'KAR', 43,NOW());

CREATE TABLE `products` (
  `ID` int(11) NOT NULL,
  `PRODUCT_ID` int(11) NOT NULL,
  `PRODUCT_NAME` text NOT NULL,
  `PRODUCT_PRICE` int(11) NOT NULL,
  `PRODUCT_ARTICLE` text NOT NULL,
  `PRODUCT_QUANTITY` int(11) NOT NULL,
  `DATE_CREATE` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
COMMIT;
